In [55]:
import pandas as pd
import numpy as np

In [56]:
car_sales_missing = pd.read_csv("car-sales-extended-missing-data.csv")
car_sales_missing

       Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

In [57]:
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [58]:
car_sales_missing.dropna(subset = "Price" , inplace = True)

In [59]:
car_sales_missing.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

In [60]:
X = car_sales_missing.drop(labels = "Price" , axis = 1) 
y = car_sales_missing["Price"]
X.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
dtype: int64

In [61]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer

catogory_impute = SimpleImputer(strategy = "constant" , fill_value = "missing")
door_impute = SimpleImputer(strategy = "constant" , fill_value = 4)
odom_impute = SimpleImputer(strategy = "mean")

catogory_name = ["Make" , "Colour"]
door_name = ["Doors"]
odom_name = ["Odometer (KM)"]

transform = ColumnTransformer( transformers= [
    ("cat" , catogory_impute , carogory_name) ,
                             ("door" , door_impute , door_name ) ,
                             ("odom", odom_impute , odom_name)])
filled = transform.fit_transform(X)
filled

array([['Honda', 'White', 4.0, 35431.0],
       ['BMW', 'Blue', 5.0, 192714.0],
       ['Honda', 'White', 4.0, 84714.0],
       ...,
       ['Nissan', 'Blue', 4.0, 66604.0],
       ['Honda', 'White', 4.0, 215883.0],
       ['Toyota', 'Blue', 4.0, 248360.0]], shape=(950, 4), dtype=object)

In [62]:
filled_df = pd.DataFrame(filled)

In [63]:
filled_df

           0      1    2         3
0      Honda  White  4.0   35431.0
1        BMW   Blue  5.0  192714.0
2      Honda  White  4.0   84714.0
3     Toyota  White  4.0  154365.0
4     Nissan   Blue  3.0  181577.0
..       ...    ...  ...       ...
945   Toyota  Black  4.0   35820.0
946  missing  White  3.0  155144.0
947   Nissan   Blue  4.0   66604.0
948    Honda  White  4.0  215883.0
949   Toyota   Blue  4.0  248360.0

[950 rows x 4 columns]

In [64]:
filled_df.head(14)

          0      1    2              3
0     Honda  White  4.0        35431.0
1       BMW   Blue  5.0       192714.0
2     Honda  White  4.0        84714.0
3    Toyota  White  4.0       154365.0
4    Nissan   Blue  3.0       181577.0
5     Honda    Red  4.0        42652.0
6    Toyota   Blue  4.0       163453.0
7     Honda  White  4.0  130987.447894
8   missing  White  4.0       130538.0
9     Honda   Blue  4.0        51029.0
10   Nissan  White  4.0       167421.0
11   Nissan  Green  4.0        17119.0
12   Nissan  White  4.0       102303.0
13  missing  White  4.0       134181.0

## now lets convert the names or catogory into numbers so the computer can understand

In [69]:
filled_df.rename(columns = { 0 : "Make" , 1 : "Colour" , 2 : "Door" , 3 : "odometer"} , inplace = True)

In [71]:
X = filled_df

In [74]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

catagory_features = ["Make" , "Colour" , "Door"]
one_hot = OneHotEncoder(sparse_output= False)
transform = ColumnTransformer([("covert_into_num" , one_hot , catagory_features) ] , remainder = 'passthrough')
transformed = transform.fit_transform(X)

In [75]:
pd.DataFrame(transformed)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,35431.0
1,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,192714.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,84714.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,154365.0
4,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,181577.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,35820.0
946,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,155144.0
947,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,66604.0
948,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,215883.0
949,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,248360.0